##database properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.properties.hibernate.hql.bulk_id_strategy=org.hibernate.hql.spi.id.inline.InlineIdsOrClauseBulkIdStrategy
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/edu365?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false
spring.datasource.username=root
spring.datasource.password=root
##Flyway configuration
spring.flyway.baselineOnMigrate=true
##security properties
edu365.app.jwtSecret=edu365SecretKey
edu365.app.jwtExpirationMs=1800000
edu365.app.refreshjwtExpirationMs=86400000
edu365.app.base-url=http://102.219.178.118:4200
#mailing properties
spring.mail.host=mail.freeacademy.tn
spring.mail.port=587
spring.mail.username=contact@freeacademy.tn
spring.mail.password=supcomSupcom20Mai2019++
spring.mail.sender=contact@freeacademy.tn
spring.mail.server.app_name=freeacademy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.ssl.trust=mail.freeacademy.tn
#spring.mail.properties.mail.ssl.trust=smtp.gmail.com
##port configuration
server.port=8099
server.servlet.contextPath=/api
server.error.include-stacktrace=never
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=0
# Max file size.
spring.servlet.multipart.max-file-size=2000MB
# Max Request Size
spring.servlet.multipart.max-request-size=2150MB
#spring.servlet.multipart.location=/home/ubuntu/otlobni/tmp
#spring.servlet.http.location=/home/ubuntu/otlobni/tmp
multipart.location=${java.io.tmpdir}
## File Storage Properties
storage.type=local
file.upload-dir=/root/edu365/files
##file.upload-dir=C:/Users/Lenovo/Desktop/FREELANCER/WorkSpace/storage
storage.spaces.key=
storage.spaces.secret=
storage.spaces.endpoint=
storage.spaces.region=
storage.spaces.bucket=
storage.remote=false
##edu365 front base url
edu365.front.base.url=http://102.219.178.104/free-academy/
edu365.front.admin.base.url=http://102.219.178.118:4200/
edu365.backend.base.url=http://102.219.178.118:8099/api/
##Jitsi meet server Properties
edu365.jitsi.token.domain=
edu365.jitsi.token.application-id=
edu365.jitsi.token.secret-key=
##edu365 Login Max Attempt
edu365.login.max-attempt=10
edu365.app.agency.firstInternalId=1500
edu365.app.invoice.startBillNumber=1046150800
edu365.email.max-attempt=3

##edu365 scheduleds crom
edu365.invoice.scheduler.cron=0 * * * * *
edu365.email.scheduler.automatic.sent.cron=0 */15 * ? * *
edu365.announcement.scheduler.automatic.finish.past.announcement.cron=0 0 0 * * ?

##edu365 cors configuration
### Example config allow multi domain: 
### edu365.cors.allowed.origins=https://agent.edu365preprod.website,https://edu365preprod.website,https://admin.edu365preprod.website
#### ==> you can use * to allow all domains
edu365.cors.allowed.origins=*
##edu365 logging configuration
logging.config=classpath:logging/log4j2-local.properties

#paramétres paiement en ligne
edu365.ext.payment.api.url=http://localhost:8099/api/ext-payment/api
###sobflous
edu365.payment.sobflous.api.base.url=https://www.sobflous.online/marchand15mHdr85lOer26gh/wsmarchand/
edu365.payment.sobflous.api.request.payment.url=https://www.sobflous.online/marchand15mHdr85lOer26gh/wsmarchand/demandepaiement
edu365.payment.sobflous.api.request.transaction.verification.url=https://www.sobflous.online/marchand15mHdr85lOer26gh/wsmarchand/verificationtransaction
edu365.payment.sobflous.shopId=231
edu365.payment.sobflous.password=AJvRNZKTrz
edu365.payment.sobflous.shopCode=35921
edu365.payment.sobflous.bonus=0
edu365.payment.sobflous.commission=2

edu365.payment.vat=19

###paymee
edu365.payment.paymee.api.base.url=https://app.paymee.tn/api/v1/payments/
edu365.payment.paymee.vendor=17377
edu365.payment.paymee.token=cdc0d7ee76bce1d88827bf8f9222f05330504dd7
edu365.payment.paymee.api.request.check.payment.url=https://app.paymee.tn/gateway/

##zoom
edu365.zoom.meeting.api.base.url=https://api.zoom.us/v2/users/me/meetings
edu365.zoom.s2sToken.api.base.url=https://zoom.us/oauth/token
edu365.zoom.meeting.accountId=PuuMum2_T5WXib6K1qqQrw
edu365.zoom.meeting.clientId=cdblRZlaSAyrZAw18cg_3Q
edu365.zoom.meeting.clientSecret=gRHel53orCnE5Nw0IQNQz37cauCPvGpw

edu365.zoom.meeting.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImlzcyI6IlVxeV95QkIyVEl1Nnk4MEhjWDhib2ciLCJleHAiOjE3MzY0NjMyNDAsImlhdCI6MTY3MzI5OTUzNH0._cr6wt4tgpAh4s8_8DgqVeloAfyKLWP-SIA_GAHG8hg


##prestation
edu365.prestation.commission=20

#registration fees
edu365.payment.registration.fees=10
