package fr.imcoding.edu365.enumeration;

public enum MediaContext {
  CIN, PICTURE_PROFIL, PICTURE_COVER,PICTURE_PROJECT,PICTURE_IDENTITY,PICTURE_GRADUATION,PICTURE_CERTIFICATE,CV_DOCUMENT,VIDEO,
  VIDEO_PRESENTATION, RIB, ANNOUNCEMENT, OFFER,PAYMENT_DOCUMENT,PRESTATION_DOCUMENT,TEACHER_COURSE
}
