package fr.imcoding.edu365.enumeration;

public enum OfferStatus {
  ACCEPTED,
  REFUSED,
  PENDING,
  PENDING_EXPERT_CONFIRMATION,
  REFUSED_BY_EXPERT,
  PENDING_CUSTOMER_PAYMENT,
  VALIDATED_AND_PAID,
  CANCELED_BY_ADVERTISER,
  CANCELED_BY_EXPERT,
  PENDING_PAYMENT_VALIDATION,
  ACCEPTED_IN_PACKAGE
}
